<?php

namespace App\Http\Controllers;

use GuzzleHttp\Client;
use Illuminate\Http\Request;

class BloombergMarketsController extends Controller
{
    public function getData($category = 'markets')
    {

        // Create a new Guzzle HTTP client instance
        $client = new \GuzzleHttp\Client();

        try {
            // Make a GET request to Bloomberg API
            $response = $client->request('GET', 'https://bb-finance.p.rapidapi.com/news/list?id='.$category, [
                'headers' => [
                    'X-RapidAPI-Host' => 'bb-finance.p.rapidapi.com',
                    'X-RapidAPI-Key' => 'eb08bc8d35msha71ae9f40453646p197000jsn6a04b7195d17',
                ],
            ]);

            // Parse and process the response
            $data = json_decode($response->getBody(), true);

            $arr = [];
        
            foreach ($data['modules'] as $module) {
                foreach ($module['stories'] as $story) {

                    $arr[] = [
                        'id' => $story['internalID'],
                        'category' => $story['primaryCategory'],
                        'title' => $story['title'],
                        'summary' => isset($story['autoGeneratedSummary']) ? $story['autoGeneratedSummary'] : $story['summary'],
                        'thumbnail' => isset($story['thumbnailImage']) ? $story['thumbnailImage'] : 'null',
                        'articleURL' => $story['shortURL'],
                        'byline' => $story['byline']
                    ];
                }
            }

            // Return the response
            return response()->json($arr);
        } catch (\Exception $e) {
            // Handle any errors
            return response()->json(['error' => $e->getMessage()], 500);
        }
    }
}
